/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javariance.bookshop;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Lakshani
 */
public class EditAuthor extends javax.swing.JFrame {

    /**
     * Creates new form EditAuthor
     */
    public EditAuthor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_EditAuthor = new javax.swing.JLabel();
        Lbl_AuthorID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Txt_AuthorID = new javax.swing.JTextField();
        Txt_AuthorName = new javax.swing.JTextField();
        Btn_Update = new javax.swing.JButton();
        Btn_Clear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_EditAuthor.setBackground(new java.awt.Color(204, 255, 255));
        Lbl_EditAuthor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Lbl_EditAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_EditAuthor.setText("Edit Author");
        Lbl_EditAuthor.setOpaque(true);
        getContentPane().add(Lbl_EditAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 398, 49));

        Lbl_AuthorID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Lbl_AuthorID.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_AuthorID.setText("Author ID");
        getContentPane().add(Lbl_AuthorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 83, 150, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Author Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 123, 150, -1));
        getContentPane().add(Txt_AuthorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 82, 138, -1));
        getContentPane().add(Txt_AuthorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 120, 138, -1));

        Btn_Update.setBackground(new java.awt.Color(204, 255, 204));
        Btn_Update.setText("Update");
        Btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 215, 80, -1));

        Btn_Clear.setBackground(new java.awt.Color(204, 255, 204));
        Btn_Clear.setText("Clear");
        Btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 215, 70, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 215, 80, -1));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ClearActionPerformed
        Txt_AuthorID.setText("");
        Txt_AuthorName.setText("");
    }//GEN-LAST:event_Btn_ClearActionPerformed

    private void Btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UpdateActionPerformed
        String ID = Txt_AuthorID.getText();
        String Name = Txt_AuthorName.getText();
        
       try{
        DBConnection con=new DBConnection();
        Connection connection=con.getDBConnection();
        Statement stmt = connection.createStatement();
        String sql= "update author set Author_Name = '"+Name+"' where Author_ID = '"+ID+"'";
        stmt.executeUpdate(sql);
        connection.close(); 
        JOptionPane.showMessageDialog(this,"You have successfully added it!");
    }                                          
        
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_Btn_UpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAuthor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Clear;
    private javax.swing.JButton Btn_Update;
    private javax.swing.JLabel Lbl_AuthorID;
    private javax.swing.JLabel Lbl_EditAuthor;
    private javax.swing.JTextField Txt_AuthorID;
    private javax.swing.JTextField Txt_AuthorName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
