/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javariance.bookshop;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author chamcbs <your.name at your.org>
 */
public class NewPublisher extends javax.swing.JFrame {

    /**
     * Creates new form NewPublisher
     */
    public NewPublisher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFieldP_Name = new javax.swing.JTextField();
        TextFieldP_TP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TextFieldP_Address = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextFieldP_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldP_NameActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldP_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 65, 206, 34));
        getContentPane().add(TextFieldP_TP, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 222, 206, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Publisher Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 75, 104, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Publisher Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 145, 110, 26));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 225, 110, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 297, 70, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 297, 80, -1));
        getContentPane().add(TextFieldP_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 131, 210, 54));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 297, 70, -1));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Publisher");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldP_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldP_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldP_NameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TextFieldP_Name.setText("");
        TextFieldP_Address.setText("");
        TextFieldP_TP.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int dialogButton = JOptionPane.YES_NO_OPTION;
         int dialogResult = JOptionPane.showConfirmDialog (null, "Would You Like to Save this details?","Warning",dialogButton);
         if(dialogResult == JOptionPane.YES_OPTION){
        
            try{
                DBConnection c = new DBConnection(); 
                c.getDBConnection();
                Statement stmt=c.getDBConnection().createStatement();
                String sql1="SELECT MAX(Publisher_ID) AS Publisher_ID FROM publisher;";
                //String sql="insert into publisher (Publisher_ID, Publisher_Name, Address, Contact_No) values ('"+TextFieldP_ID.getText()+"','"+TextFieldP_Name.getText()+"','"+TextAreaP_Address.getText()+"','"+TextFieldP_TP.getText()+"')";
                ResultSet rs=stmt.executeQuery(sql1);
                         
                 while(rs.next()){
                    String P_ID =rs.getString("Publisher_ID");
                    String splitted_P_ID = P_ID.replace("PU", "");
                    int num_P_ID=Integer.parseInt(splitted_P_ID);
                    num_P_ID=num_P_ID+1;
                    
                    String new_splitted_P_ID = String.valueOf(num_P_ID);
                    String new_P_ID ="PU"+new_splitted_P_ID;

                    Statement stmt2=c.getDBConnection().createStatement();
                    String sql2="insert into publisher (Publisher_ID, Publisher_Name, Address, Contact_No) values ('"+new_P_ID+"','"+TextFieldP_Name.getText()+"','"+TextFieldP_Address.getText()+"','"+TextFieldP_TP.getText()+"')";
                    stmt2.executeUpdate(sql2);
                    c.getDBConnection().close();
                }
         
                TextFieldP_Name.setText("");
                TextFieldP_Address.setText("");
                TextFieldP_TP.setText("");
                
                
        
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Something goes wrong!!! Please try again");
                System.out.println("Error in connecting to database: "+e);
            }
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPublisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPublisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPublisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPublisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPublisher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldP_Address;
    private javax.swing.JTextField TextFieldP_Name;
    private javax.swing.JTextField TextFieldP_TP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
